openapi: 3.0.0
info:
  title: Expiry Tracker API - Documents
  version: 1.0.0
  description: CRUD endpoints for document management with file uploads

servers:
  - url: http://localhost:3000/api
    description: Local development
  - url: https://api.expirytracker.com/api
    description: Production

paths:
  /documents:
    get:
      summary: Get all documents for current user
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [Expired, Expiring Soon, Safe]
          description: Filter by status
        - name: type
          in: query
          schema:
            type: string
          description: Filter by document type
        - name: sort
          in: query
          schema:
            type: string
            enum: [expiry_asc, expiry_desc, type_asc, type_desc, created_asc, created_desc]
            default: expiry_asc
          description: Sort order
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
          description: Items per page
      responses:
        '200':
          description: Documents retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Document'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new document
      tags:
        - Documents
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - type
                - number
                - expiryDate
              properties:
                type:
                  type: string
                  enum: [Passport, Driver License, ID Card, Insurance Policy, Medical Record, Visa, Vehicle Registration, Professional License, Other]
                  example: Passport
                number:
                  type: string
                  maxLength: 100
                  example: AB1234567
                expiryDate:
                  type: string
                  format: date
                  example: 2028-06-30
                file:
                  type: string
                  format: binary
                  description: Document file (PDF, JPG, JPEG, PNG, max 10MB)
      responses:
        '201':
          description: Document created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Document created successfully
                  data:
                    $ref: '#/components/schemas/Document'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: File size must be under 10MB

  /documents/{id}:
    get:
      summary: Get a specific document
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Document ID
      responses:
        '200':
          description: Document retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Document'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a document
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Document ID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [Passport, Driver License, ID Card, Insurance Policy, Medical Record, Visa, Vehicle Registration, Professional License, Other]
                  example: Passport
                number:
                  type: string
                  maxLength: 100
                  example: AB1234567
                expiryDate:
                  type: string
                  format: date
                  example: 2028-06-30
                file:
                  type: string
                  format: binary
                  description: New document file (replaces existing)
      responses:
        '200':
          description: Document updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Document updated successfully
                  data:
                    $ref: '#/components/schemas/Document'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '413':
          description: File too large
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: File size must be under 10MB

    delete:
      summary: Delete a document
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Document ID
      responses:
        '200':
          description: Document deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Document deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /documents/{id}/file:
    get:
      summary: Download document file
      tags:
        - Documents
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Document ID
      responses:
        '200':
          description: File download URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        example: https://storage.example.com/documents/abc123.pdf?signature=xyz
                      expiresAt:
                        type: string
                        format: date-time
                        example: 2026-01-23T16:00:00Z
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Document or file not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Document file not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Document:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: integer
          example: 1
        type:
          type: string
          enum: [Passport, Driver License, ID Card, Insurance Policy, Medical Record, Visa, Vehicle Registration, Professional License, Other]
          example: Passport
        number:
          type: string
          example: AB1234567
        expiryDate:
          type: string
          format: date
          example: 2028-06-30
        filePath:
          type: string
          example: documents/abc123-passport.pdf
        fileSize:
          type: integer
          example: 2048576
        mimeType:
          type: string
          example: application/pdf
        status:
          type: string
          enum: [Expired, Expiring Soon, Safe]
          example: Safe
        remainingDays:
          type: integer
          example: 888
        createdAt:
          type: string
          format: date-time
          example: 2026-01-23T10:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2026-01-23T10:00:00Z

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 50
        total:
          type: integer
          example: 25
        totalPages:
          type: integer
          example: 1

  responses:
    Unauthorized:
      description: Unauthorized - Invalid or missing token
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Unauthorized

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Validation error
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: expiryDate
                    message:
                      type: string
                      example: Expiry date is required

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Document not found
