openapi: 3.0.0
info:
  title: Expiry Tracker API - Food Items
  version: 1.0.0
  description: CRUD endpoints for food item management

servers:
  - url: http://localhost:3000/api
    description: Local development
  - url: https://api.expirytracker.com/api
    description: Production

paths:
  /food-items:
    get:
      summary: Get all food items for current user
      tags:
        - Food Items
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [Expired, Expiring Soon, Safe]
          description: Filter by status
        - name: category
          in: query
          schema:
            type: string
          description: Filter by category
        - name: storage_type
          in: query
          schema:
            type: string
          description: Filter by storage type
        - name: sort
          in: query
          schema:
            type: string
            enum: [expiry_asc, expiry_desc, name_asc, name_desc, created_asc, created_desc]
            default: expiry_asc
          description: Sort order
        - name: page
          in: query
          schema:
            type: integer
            default: 1
          description: Page number
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
          description: Items per page
      responses:
        '200':
          description: Food items retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/FoodItem'
                      pagination:
                        $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new food item
      tags:
        - Food Items
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - category
                - expiryDate
                - storageType
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: Milk
                category:
                  type: string
                  enum: [Dairy, Meat, Vegetables, Fruits, Grains, Beverages, Condiments, Frozen, Canned, Other]
                  example: Dairy
                expiryDate:
                  type: string
                  format: date
                  example: 2026-02-15
                quantity:
                  type: string
                  maxLength: 100
                  example: 1 liter
                storageType:
                  type: string
                  enum: [Refrigerator, Freezer, Pantry, Counter]
                  example: Refrigerator
      responses:
        '201':
          description: Food item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Food item created successfully
                  data:
                    $ref: '#/components/schemas/FoodItem'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /food-items/{id}:
    get:
      summary: Get a specific food item
      tags:
        - Food Items
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Food item ID
      responses:
        '200':
          description: Food item retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/FoodItem'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a food item
      tags:
        - Food Items
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Food item ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: Milk
                category:
                  type: string
                  enum: [Dairy, Meat, Vegetables, Fruits, Grains, Beverages, Condiments, Frozen, Canned, Other]
                  example: Dairy
                expiryDate:
                  type: string
                  format: date
                  example: 2026-02-15
                quantity:
                  type: string
                  maxLength: 100
                  example: 1 liter
                storageType:
                  type: string
                  enum: [Refrigerator, Freezer, Pantry, Counter]
                  example: Refrigerator
      responses:
        '200':
          description: Food item updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Food item updated successfully
                  data:
                    $ref: '#/components/schemas/FoodItem'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a food item
      tags:
        - Food Items
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Food item ID
      responses:
        '200':
          description: Food item deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Food item deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FoodItem:
      type: object
      properties:
        id:
          type: integer
          example: 1
        userId:
          type: integer
          example: 1
        name:
          type: string
          example: Milk
        category:
          type: string
          enum: [Dairy, Meat, Vegetables, Fruits, Grains, Beverages, Condiments, Frozen, Canned, Other]
          example: Dairy
        expiryDate:
          type: string
          format: date
          example: 2026-02-15
        quantity:
          type: string
          example: 1 liter
        storageType:
          type: string
          enum: [Refrigerator, Freezer, Pantry, Counter]
          example: Refrigerator
        status:
          type: string
          enum: [Expired, Expiring Soon, Safe]
          example: Safe
        remainingDays:
          type: integer
          example: 23
        createdAt:
          type: string
          format: date-time
          example: 2026-01-23T10:00:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2026-01-23T10:00:00Z

    Pagination:
      type: object
      properties:
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 50
        total:
          type: integer
          example: 150
        totalPages:
          type: integer
          example: 3

  responses:
    Unauthorized:
      description: Unauthorized - Invalid or missing token
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Unauthorized

    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Validation error
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                      example: expiryDate
                    message:
                      type: string
                      example: Expiry date is required

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: Food item not found
